version: '3.1'

services:
  mongodb:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  app:
    build: .
    container_name: task_api
    ports:
      - 3000:3000
    